### ISSUE TITLE
I need to add this to my test

### ISSUE THREAD

**Issue by rdebath** [KrokodileGlue/bfi#1]
This hello world doesn't work because your optimisation condition is incomplete.
```bf
++++++++[->+++++++++<]>.----[--<+++>]<-.+++++++..+++.[--->+<]>-----.---[
-<+++>]<.---[--->++++<]>-.+++.------.--------.-[---<+>]<.[--->+<]>-.<
```

**Comment by KrokodileGlue** [comment]
Uh oh, that's embarrassing! Working on a bit of a rewrite, since this project is a few months old now, I will be sure to fix that.

**Comment by KrokodileGlue** [comment]
Fixed in the first release.

**Comment by rdebath** [comment]
Looking good, of the short tests [100k cells](https://github.com/rdebath/Brainfuck/blob/master/testing/cells100k.b) fails for obvious reasons. But it does trip over [Skip loop](https://github.com/rdebath/Brainfuck/blob/master/testing/Skiploop.b)

**Comment by KrokodileGlue** [comment]
Forgot the C type promotion rules for a second, fixed it. :P
